# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc22f2f93f021457de85725918dba7c4e07f521134061c89d3d7e4494885efda305a1b65e6532eaed45b21e56cb13cb453f9b31d41b660a0c6d07a6c74f1f5af

test:
  secret_key_base: 1e1026f722aa18baccbd2bd8526d2f1a6b8f053e655fedfc06f11d80609649a1f33da4ee1fa41404edbcdcd067a41a89d1627cf8b3324a2bce83bd91bc29027f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
